export const spokenLanguageList = [
    "Spanish",
    "German",
    "Russian",
    "Turkish",
    "Swedish",
    "Norwegian",
    "Danish",
    "French",
    "Italian",
    "Portuguese",
    "Dutch",
    "Polish",
    "English",
    "Mandarian",
    "Arabian"
]

export const categoryList = [
    "Actress X",
    "Apartment rental",
    "Couple",
    "Escort (sex)",
    "Hostess",
    "Masseuse (not sex)",
    "Living room",
    "SM dominatrix",
    "Treanssexual"
]

export const servicesList = [
    "69",
    "Rimming",
    "Fucking tits",
    "Coffee pipe",
    "Couple",
    "Cunnilingus",
    "Soft domination",
    "Double Penetration",
    "Duo Lesbo Show",
    "Body Ejaculation",
    "Facial cumshot",
    "Facesitting",
    "Blow Job",
    "Fetish",
    "French Kiss",
    "Girlfriend Experience",
    "Deep Throat",
    "Role Play Game",
    "Lingerie",
    "Erotic Massage",
    "Masturbation",
    "Pornstar Experience",
    "Sexual Intercourse",
    "VIP Services",
    "Sex Toy",
    "Group Sex",
    "Sodomy",
    "Striptase"
]

export const silhouetteList = [
    "Slim",
    "Delicate",
    "By",
    "Athletic",
    "Pulpy",
    "Round"
]

export const originList = [
    "European",
    "Asian",
    "Latin",
    "African",
    "Swiss",
    "Russian",
    "Metissé"
]

export const cityList = [
    "Aarberg", 
    "Belp", 
    "Bern", 
    "Biel/Bienne", 
    "Büren a.A.", 
    "Burgdorf", 
    "Erlach", 
    "Huttwil", 
    "Interlaken", 
    "Ittigen", 
    "Köniz", 
    "La Neuveville", 
    "Langenthal", 
    "Laupen", 
    "Lyss", 
    "Moutier", 
    "Münchenbuchsee", 
    "Münsingen", 
    "Muri bei Bern", 
    "Nidau", 
    "Ostermundigen", 
    "Spiez", 
    "Steffisburg",
    "Thun", 
    "Unterseen", 
    "Wangen an der Aare",
    "Wiedlisbach",
    "Zollikofen",
    "Bulle", 
    "Châtel-Saint-Denis", 
    "Estavayer-le-Lac", 
    "Fribourg",
    "Gruyères", 
    "La Tour-de-Trême", 
    "Murten", 
    "Romont", 
    "Rue", 
    "Villars-sur-Glâne",
    "Bourg-Saint-Pierre", 
    "Brig-Glis", 
    "Conthey", 
    "Leuk", 
    "Martigny", 
    "Monthey", 
    "Orsières", 
    "Saillon", 
    "Saint-Maurice", 
    "Sembrancher", 
    "Sierre", 
    "Sion", 
    "Visp", 
    "Zermatt",
    "Aigle", 
    "Aubonne", 
    "Avenches", 
    "Bussigny", 
    "Coppet", 
    "Cossonay", 
    "Crissier", 
    "Cudrefin", 
    "Cully", 
    "Échallens", 
    "Ecublens", 
    "Gland", 
    "Grandcour", 
    "Grandson", 
    "La Sarraz", 
    "La Tour-de-Peilz", 
    "Lausanne", 
    "Les Clées", 
    "Lutry", 
    "Montreux", 
    "Morges", 
    "Moudon", 
    "Nyon", 
    "Orbe", 
    "Payerne", 
    "Prilly", 
    "Pully", 
    "Renens", 
    "Rolle", 
    "Vevey", 
    "Saint-Prex", 
    "Vevey", 
    "Villeneuve", 
    "Yverdon-les-Bains"
]
